autoCloseIssue: true
autoLinkIssue: true
openDraftPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
conventionalPrTitles: true
defaultBranch: 'master/dev'
branches:
  - label: NoBranch
    skip: true
  - label: question
    skip: true
  - label: wontfix
    skip: true
  - label: documentation
    prefix: doc/
    prTarget: 'master/dev'
  - label:
    - bug
    - URGENT
    name: main
    prefix: hotfix/
    prTarget: 'main'
  - label: New feature
    name: dev
    prefix: feature/
    prTarget: 'master/dev'
  - label: enhancement
    name: dev
    prefix: feature/
    prTarget: 'master/dev'

