autoCloseIssue: true
defaultBranch: 'master/dev'
branches:
  - label: NoBranch
    skip: true
  - label: question
    skip: true
  - label: wontfix
    skip: true
  - label: documentation
    skip: true
  - label:
    - bug
    - URGENT
    name: main
    prefix: hotfix/
  - label: New feature
    name: dev
    prefix: feature/

